Fix undefined reference to get_structure() method
This commit works around a bug with Sphinx not generating
any links for method references, that reference inherited
methods (see also https://github.com/sphinx-doc/sphinx/issues/10699)

Since, a Warning is trigger by Sphinx for the "missing"
reference, the docs build will fail. Therefore, this commit
removes the offending reference from the docs.